# HASH CODE 2018

In [1]:
import numpy as np
import sys

In [2]:
file = open("c_no_hurry.in", "r") 
vett=file.readlines()
file.close()
def removeEnter(vett):
    for i in range(len(vett)):
        vett[i]=vett[i].replace("\n","")
    return vett
vett=removeEnter(vett)
vett

['3000 2000 81 10000 1 200000',
 '1795 1043 2296 1955 0 200000',
 '144 1933 1934 467 0 200000',
 '1700 833 10 1987 0 200000',
 '1473 1815 2821 810 0 200000',
 '1372 478 1210 150 0 200000',
 '2787 12 1232 30 0 200000',
 '2314 563 1341 419 0 200000',
 '2492 339 1037 1432 0 200000',
 '1551 805 1322 331 0 200000',
 '2664 491 45 767 0 200000',
 '2390 210 2019 215 0 200000',
 '2954 449 2164 1905 0 200000',
 '708 1681 2580 701 0 200000',
 '1545 664 1460 585 0 200000',
 '520 1715 819 634 0 200000',
 '1932 1600 301 985 0 200000',
 '2443 54 990 935 0 200000',
 '1886 1121 2736 1503 0 200000',
 '761 1085 1711 567 0 200000',
 '938 1807 1926 1185 0 200000',
 '470 1739 1963 324 0 200000',
 '2031 325 2397 802 0 200000',
 '202 247 390 614 0 200000',
 '1188 972 3 605 0 200000',
 '1493 1783 648 1358 0 200000',
 '1220 803 1448 1494 0 200000',
 '402 487 498 1092 0 200000',
 '2108 1973 2680 1646 0 200000',
 '1743 688 1281 766 0 200000',
 '2936 1544 2854 877 0 200000',
 '2147 1716 2690 315 0 200000',
 '1297 

In [3]:
firstRow=vett[0].split(" ")
rows=int(firstRow[0])
columns=int(firstRow[1])
cars=int(firstRow[2])
rides=int(firstRow[3])
bonus=int(firstRow[4])
steps=int(firstRow[5])
print("First row = ",firstRow)

First row =  ['3000', '2000', '81', '10000', '1', '200000']


In [4]:
data=np.empty([len(vett)-1,6])
for i in range(1,len(vett)):
    data[i-1]=vett[i].split(" ")

In [5]:
def distanceTwoPoint(r1,c1,r2,c2):
    dist=abs(r2-r1)+abs(c2-c1)
    return abs(dist)
startEndDist=np.empty([rides])
for i in range(rides):
    startEndDist[i]=distanceTwoPoint(data[i,0],data[i,1],data[i,2],data[i,3])

In [6]:
carsProp=np.zeros([cars,3])#X, Y, delay

In [7]:
carRide=[""]*cars

### A ciascuna corsa devo assegnare un'auto
Assegno una corsa ad un auto, aggiorno la posizione di quell'auto, ricalcolo le distanze (sommando a ciascuna auto usata il tempo in più che ha già usato) e seleziono l'auto con la distanza minore da un punto

In [8]:
def distanceCarsStartRide(n):
    distances=np.zeros([cars])
    for i in range(cars):
        distances[i]=distanceTwoPoint(data[n,0],data[n,1],carsProp[i,0],carsProp[i,1])+carsProp[i,2]
    return distances

def selectBestChoice(n):
    distances=distanceCarsStartRide(n)
    bestIndex=np.argmin(distances)
    carRide[bestIndex]=str(carRide[bestIndex])+" "+str(n)
    #Change proprieties of the car I used
    carsProp[bestIndex,0]=data[bestIndex,2]
    carsProp[bestIndex,1]=data[bestIndex,3]
    i=bestIndex
    carsProp[i,2]=carsProp[i,2]+startEndDist[n]+data[n,4]+distanceTwoPoint(carsProp[i,0],carsProp[i,1],data[n,0],data[n,1])

def distFromOrigin():
    distFromOrigin=np.zeros([rides])
    for i in range(rides):
        wait=data[i,4]-(data[i,0]+data[i,1])
        if wait>0:
            distFromOrigin[i]=data[i,0]+data[i,1]+wait
        else:
            distFromOrigin[i]=data[i,0]+data[i,1]
    return distFromOrigin

In [9]:
def bestCarForRide(n):
    best=sys.maxsize
    bestIndex=0
    for i in range(cars):
        dist=distanceTwoPoint(carsProp[i,0],carsProp[i,1],data[n,0],data[n,1])+carsProp[i,2]+startEndDist[n]
        if(dist<best):
            best=dist
            bestIndex=i
    return best
            
def distancesCarToRide(v):
    distances=np.zeros([rides])
    positive=v[v>=0]
    for i in positive:
        distances[i]=bestCarForRide(i)
    distances[distances==0]=sys.maxsize
    return distances

In [10]:
v=np.arange(rides)
distances=distancesCarToRide(v)
whenStart=data[:,4]
whenFinish=data[:,5]
distOrigin=distFromOrigin()
for i in range(rides):
    #distances=distancesCarToRide(v)
    bestRide=np.argmin(whenStart)
    selectBestChoice(bestRide)
    whenStart[bestRide]=sys.maxsize
    #v[bestRide]=-1

In [11]:
v=np.arange(5)
v[1]=0
v[v==0]=5
v

array([5, 5, 2, 3, 4])

In [12]:
for i in carRide:
    numberOfRides=len(i.split(" "))-1
    print(str(numberOfRides)+i)

119 0 27 151 182 214 248 379 447 570 686 776 844 948 1057 1104 1171 1284 1434 1531 1624 1716 1828 1931 1999 2028 2139 2206 2339 2364 2428 2510 2592 2623 2691 2838 2955 3050 3233 3310 3424 3521 3632 3760 3822 3954 3978 3992 4064 4119 4186 4266 4361 4460 4564 4687 4757 4859 4989 5092 5178 5280 5408 5452 5489 5523 5588 5667 5784 5837 5973 6108 6257 6372 6423 6512 6598 6659 6758 6789 6921 7040 7117 7208 7279 7324 7449 7467 7562 7582 7648 7688 7735 7828 7940 8026 8113 8197 8275 8328 8361 8464 8529 8642 8712 8780 8883 8976 9112 9179 9230 9278 9394 9467 9549 9624 9698 9834 9902 9930
128 1 268 306 353 477 554 628 708 721 840 918 1014 1097 1129 1223 1286 1354 1447 1572 1685 1793 1883 2021 2085 2107 2151 2233 2319 2377 2507 2590 2674 2727 2818 2866 2965 3007 3051 3179 3231 3352 3485 3553 3623 3707 3755 3832 3881 3960 3991 4107 4172 4295 4404 4474 4556 4648 4670 4736 4885 4944 4985 5090 5106 5228 5274 5349 5436 5535 5583 5719 5776 5872 5930 6026 6053 6136 6211 6247 6289 6342 6433 6478 6616 6694 6

## Analyze data

In [13]:
whenFinish=data[:,5]
bonus=data[:,4]

In [14]:
whenFinish

array([ 200000.,  200000.,  200000., ...,  200000.,  200000.,  200000.])

In [15]:
bonus

array([  2.14748365e+09,   2.14748365e+09,   2.14748365e+09, ...,
         2.14748365e+09,   2.14748365e+09,   2.14748365e+09])

In [16]:
print(len(whenFinish))
print(len(np.unique(whenFinish)))

10000
1


In [17]:
print(len(bonus))
print(len(np.unique(bonus)))

10000
1
